services:
  news-publisher:
    image: constructure-news-publisher:latest
    build: .
    container_name: news-publisher
    restart: "no"
    network_mode: host
    env_file:
      - path: ./.env.local
        required: false
    environment:
      NP_STATE_PATH: "/data/distributor-state.json"
      NP_HISTORY_PATH: "/data/distributor-history.json"
      NP_LOCK_PATH: "/data/distributor-run.lock"
      NP_CACHE_PATH: "/data/hourly-news-cache.json"
    volumes:
      - ./data:/data
